# Generated by Django 3.2.10 on 2021-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('discount_card_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
