# Generated by Django 3.2.10 on 2021-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'surname', 'phone_number']},
        ),
        migrations.AlterField(
            model_name='client',
            name='discount_card_code',
            field=models.CharField(blank=True, help_text="Optional: Please pass the client's discount card code.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text="Optional: Please pass the client's email.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text="Please pass the client's name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text="Please pass the client's phone number.", max_length=9),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(help_text="Please pass the client's surname.", max_length=100),
        ),
    ]
