# Generated by Django 3.2.10 on 2021-12-15 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20211213_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text="Please pass the client's phone number.", max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
