# Generated by Django 3.2.10 on 2022-01-07 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_column='miasto', help_text='Please pass the name of the city.', max_length=100)),
                ('street', models.CharField(db_column='ulica', help_text='Please pass the name of the street.', max_length=100)),
                ('number', models.PositiveIntegerField(db_column='nr_ulicy', help_text='Please pass the number of a house.')),
                ('post_code', models.CharField(db_column='kod_pocztowy', help_text='Please pass the postal code.', max_length=6)),
                ('country', models.CharField(db_column='kraj', help_text='Please pass the name of the copuntry.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'Adresy',
                'ordering': ['country', 'city', 'street', 'number'],
                'unique_together': {('city', 'street', 'number', 'post_code', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='numer', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='data_zlozenia', help_text='Please pass the date in YYYY-MM-DD format.')),
                ('status', models.CharField(db_column='status', help_text='Please pass the status of the order.', max_length=100)),
                ('comment', models.TextField(blank=True, db_column='komentarz', help_text='Optional: Please add some comments.', max_length=1000, null=True)),
                ('address', models.ForeignKey(db_column='id_adresu', help_text='Please choose the address.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address')),
                ('client', models.ForeignKey(db_column='id_klienta', help_text='Please select the client. If client do not exist define the client in Clients section.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('employee', models.ForeignKey(db_column='id_pracownika', help_text='Please select the employee responsible for the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'db_table': 'Zamowienia',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='data', help_text='Please pass the date of the payment.')),
                ('amount', models.FloatField(db_column='kwota', help_text='Please pass the amount of the payment.', validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(db_column='numer_zamowienia', help_text='Please select the order for which the payment was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'db_table': 'Platnosci',
                'ordering': ['-date'],
                'unique_together': {('date', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ItemInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='ilosc_zamawiana', help_text='Please define quantity of product.')),
                ('delivery', models.ForeignKey(db_column='id_dostawy', help_text='Please select the delivery of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.delivereditems')),
                ('order', models.ForeignKey(db_column='numer_zamowienia', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'Pozycje_w_zamowieniach',
                'ordering': ['quantity'],
                'unique_together': {('delivery', 'order')},
            },
        ),
    ]
