# Generated by Django 3.2.10 on 2021-12-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211210_2107'),
        ('orders', '0002_auto_20211211_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminorder',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.delivereditems'),
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
        ),
    ]
