# Generated by Django 3.2.10 on 2021-12-13 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20211213_2301'),
        ('clients', '0003_auto_20211213_2301'),
        ('products', '0008_auto_20211213_2301'),
        ('orders', '0009_alter_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country', 'city', 'street', 'number'], 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='iteminorder',
            options={'ordering': ['quantity']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Please pass the name of the city.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Please pass the name of the copuntry.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(help_text='Please pass the number of a house.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(help_text='Please pass the postal code.', max_length=6),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Please pass the name of the street.', max_length=100),
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='delivery',
            field=models.ForeignKey(help_text='Please select the delivery of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.delivereditems'),
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Please define quantity of product.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(help_text='Please choose the address.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Please select the client. If client do not exist define the client in Clients section.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(help_text='Optional: Please add some comments.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(help_text='Please pass the date in YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(help_text='Please select the employee responsible for the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(help_text='Please pass the status of the order.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(help_text='Please pass the amount of the payment.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(help_text='Please pass the date of the payment.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(help_text='Please select the order for which the payment was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
