# Generated by Django 3.2.10 on 2021-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20211213_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional: Please add some comments.', max_length=1000, null=True),
        ),
    ]
