# Generated by Django 3.2.10 on 2021-12-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('city', 'street', 'number', 'post_code', 'country')},
        ),
    ]
