# Generated by Django 3.2.10 on 2021-12-11 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
