# Generated by Django 3.2.10 on 2021-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20211213_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Please pass the name of the position.', max_length=100, unique=True),
        ),
    ]
