# Generated by Django 3.2.10 on 2021-12-15 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hours_per_week',
            field=models.PositiveIntegerField(help_text='Please pass the number of hours per week of the employee.', validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Please pass the phone number of the employee.', max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
