# Generated by Django 3.2.10 on 2021-12-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211210_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivereditems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='wholesaler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wholesaler'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producer'),
        ),
    ]
