# Generated by Django 3.2.10 on 2021-12-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='overcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
