# Generated by Django 3.2.10 on 2021-12-11 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_overcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivereditems',
            name='unit_purchase_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='unit_selling_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
