# Generated by Django 3.2.10 on 2021-12-13 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211213_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Please pass the name of the category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='overcategory',
            field=models.ForeignKey(blank=True, help_text='Optional: Please select an overcategory.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='date',
            field=models.DateField(help_text='Please pass the date of the delivery.'),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='product',
            field=models.ForeignKey(help_text='Please select the product that has been delivered.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Please pass the quantity of the delivered items.'),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='unit_purchase_price',
            field=models.FloatField(help_text='Please pass the unit purchase price of the delivered items.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='unit_selling_price',
            field=models.FloatField(help_text='Please pass the unit selling price of the delivered items.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='delivereditems',
            name='wholesaler',
            field=models.ForeignKey(help_text='Please select the wholesaler of the delivered items.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wholesaler'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(help_text='Please pass the name of the producer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='producer',
            name='website',
            field=models.CharField(help_text='Please pass the website of the producer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Please select the category of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(help_text='Please pass the code of the product.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Please pass the description of the product.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Please pass the name of the product.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(help_text='Please select the producer of the producer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producer'),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='name',
            field=models.CharField(help_text='Please pass the name of the wholesaler.', max_length=100),
        ),
    ]
