# Generated by Django 3.2.10 on 2021-12-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211213_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Please pass the name of the category.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(help_text='Please pass the name of the producer.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='name',
            field=models.CharField(help_text='Please pass the name of the wholesaler.', max_length=100, unique=True),
        ),
    ]
