# Generated by Django 3.2.10 on 2021-12-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_delivereditems_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveBigIntegerField(help_text='Please pass the code of the product.', primary_key=True, serialize=False),
        ),
    ]
